baseURL = "https://example.com/"
languageCode = "en-us"
title = "Amnix"
theme = "amnix"
paginate = 10

[Params]
  description = "Responsive and configurable Hugo theme"
  columns = 2

[Params.Entry]
  meta = ["date"]
  share = ["facebook", "twitter", "reddit"]

[Params.Sidebar]
  widgets = ["recent", "categories", "tags"]

[Params.Widgets]
  recentDate = true
