baseURL = "https://example.com/"
languageCode = "en-us"
title = "Amnix"
theme = "amnix"
paginate = 10

[Params]
  description = "Responsive and configurable Hugo theme"
  columns = 2

[Params.Sidebar]
  widgets = ["recent", "categories", "tags"]

[Params.Widgets]
  recentDate = true

[Params.Share]
  facebook = true
  twitter = true
  reddit = true
