name: Test

on:
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
  pull_request:
    paths-ignore:
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hugo-version:
          - '0.54.0' # min version
          - '0.58.2' # https://github.com/gohugoio/hugoThemes/issues/682
          - '0.59.1' # last major version without goldmark renderer
          - '0.60.1' # first major version with goldmark renderer
          - 'latest'
      fail-fast: true

    steps:
      - uses: actions/checkout@v2

      - name: Run Hugo ${{ matrix.hugo-version }}
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ matrix.hugo-version }}
          # extended: true

      - name: Build with Hugo ${{ matrix.hugo-version }}
        working-directory: exampleSite
        run: HUGO_THEME="Amnix" hugo --themesDir ../.. --i18n-warnings -v
